### ISSUE TITLE
Explanation size of weights array Encoder

### ISSUE THREAD

**Issue by msche** [ogmacorp/AOgmaNeo#4]
Dear AOgmaNeo team,

I'm going through the code in an attempt to understand how SPH is working and during that I saw the size of the weight's matrix/array is set to $\text{number of hidden cells} \times area \times \text{number of cells in column}$, (my translation of [encoder.cppL245](https://github.com/ogmacorp/AOgmaNeo/blob/b2c4e38d0388de309f7cf70471430a87063cb181/source/aogmaneo/encoder.cpp#L245)). I don't understand why the multiplication with the number of cells in a column is required.

**Comment by 222464** [comment]
Hi,

Thank you for your interest in AOgmaNeo!

The weight matrix represents local receptive fields, so each cell has a receptive field area (the same area for all cells in a hidden column), where each column in that area has input/visible cells.

Put another way, each hidden cell has a 3D volume of input/visible cells it is connected to. Keep in mind that columns are either full connected to each other or not at all - so it's the chosen area that is the selective part. That's why the 3D volume is area * vld.size.z, so it spans some area of columns but full columns (full coverage across the visible column dimension).

I hope this makes sense!

**Comment by msche** [comment]
Thanks for the reply but it is not entirely clear to me yet. The part that each hidden cell has a 3D volume of input/visible cells I get and I think that is taken care of by $\text{number of hidden cells} \times area$. 

What I don't get yet is the part about the full connected to each other or not and how this relates to the multiplying with the number of cells in a column.

**Comment by msche** [comment]
Had another thorough look and I got it. Thanks for the clarification.
